/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Pagination/Pagination`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../questions/questions`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/avatar`; params?: Router.UnknownInputParams; } | { pathname: `/hub`; params?: Router.UnknownInputParams; } | { pathname: `/info`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/resultado`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Pagination/Pagination`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Button/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../questions/questions`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/avatar`; params?: Router.UnknownOutputParams; } | { pathname: `/hub`; params?: Router.UnknownOutputParams; } | { pathname: `/info`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `/resultado`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/quiz/index${`?${string}` | `#${string}` | ''}` | `/../components/Pagination/Pagination${`?${string}` | `#${string}` | ''}` | `/../components/Button/Button${`?${string}` | `#${string}` | ''}` | `/../questions/questions${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/avatar${`?${string}` | `#${string}` | ''}` | `/hub${`?${string}` | `#${string}` | ''}` | `/info${`?${string}` | `#${string}` | ''}` | `/quiz/quiz${`?${string}` | `#${string}` | ''}` | `/resultado${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Pagination/Pagination`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../questions/questions`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/avatar`; params?: Router.UnknownInputParams; } | { pathname: `/hub`; params?: Router.UnknownInputParams; } | { pathname: `/info`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/resultado`; params?: Router.UnknownInputParams; };
    }
  }
}
